# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
# Changed from 2.0 to 2.1 so orbs can be used.
version: 2.1
executors:
  core-executor:
      docker:
        - image: circleci/golang:1.11        
commands:
  build-pocket-image:
    steps:
      - checkout
      - run: dep ensure
      - run: go build cmd/pocket_core/main.go
      - run: go test ./tests/unit/...
      - run: go test ./tests/bdd/...
  local_image_scan:
    steps:
       - checkout
       - run:
          name: Building Pocket Container 
          command: docker build -t ${CIRCLE_PROJECT_REPONAME}:ci .
       - anchore/analyze_local_image:
          dockerfile_path: ./Dockerfile
          image_name: ${CIRCLE_PROJECT_REPONAME}:ci
          timeout: '500'
  slack-notification:
    steps:
      - run: exit 0
      - slack/status:
          fail_only: true
          mentions: ''
          only_for_branches:
jobs:
  build:
    executor: core-executor
    steps:
      - build-pocket-image
    working_directory: /go/src/github.com/pokt-network/pocket-core
  image_scan:
    executor: anchore/anchore_engine
    steps:
      - local_image_scan
orbs:
  anchore: anchore/anchore-engine@1.6.0
  slack: circleci/slack@3.4.0
workflows:
  pocket-workflow:
    jobs:
      build-pocket-image
      local_image_scan
      slack-notificacion